### ISSUE TITLE
There is a stupid gcc issue that affect DirectX-Headers

### ISSUE THREAD

**Issue by lygstate** [microsoft/DirectX-Headers#62]
https://news.russellsaw.io/article?id=art_4qfDEhAdkMA

**Comment by jenatali** [comment]
Yep, thanks for raising it. Looks like the state of the world is:

On Windows, we build D3D12 using C++. For WSL, we do the same, just recompiling. So for us, the C++ signatures are the source of truth.

For WINE, the headers are intended so that components like vkd3d can implement D3D12 in C, and have it match the MSVC ABI, so that Windows apps will be able to call it correctly.

If you have a C++ app using the WINE headers to target D3D12 for WSL, or a C app using our headers to target WSL, those are broken, as is a C++ using our headers to target WINE (vkd3d) directly.

Sounds like I need to go hack up MIDL again to support emitting the Linux ABI C definitions alongside the MSVC ABI. Otherwise Dozen is going to have a hard time working in WSL.

**Comment by lygstate** [comment]
I have a draft PR  to fixes this, mesa wgl are passed in msys2.

**Comment by jenatali** [comment]
I didn't add the inline definitions to the API header, because that makes it impossible to take the address of the function, but now GCC-compatible definitions of the interface are available in the header. The only thing missing on the Mesa side is to add some simple ABI wrappers to call the right version.

**Comment by lygstate** [comment]
I am worried that https://github.com/microsoft/DirectX-Headers/commit/35f2aa9c9e06e70aa45b9f4928262c46ec7975cf are pushed to hurry, it's looks like the C Virtual Table also been changed.

**Comment by lygstate** [comment]
It's better split into two commit, one is update the IDL file, the other one is support for mingw, otherwise too huge to review

**Comment by jenatali** [comment]
To be clear, I was not asking for review. We've reviewed the MIDL changes internally. The C changes were also intentional.

I'll consider adding a macro to force the ABI version of the C++ definitions, but for now that'll be a problem for MinGW consumers of this project to deal with.
